//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmnettsted.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }
        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-mm-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Releasedate { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string Duration { get; set; }
    
        public virtual Genres Genres { get; set; }
        public virtual Languages Languages { get; set; }
    }
}
