//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmnettsted.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Registration
    {
        [Key]
        public int UserId { get; set; }
        [Required(ErrorMessage = "Please enter your First Name")]
        [Display(Name = "First Name")]
        public string Firstname { get; set; }
        [Required(ErrorMessage = " Please enter your Last Name")]
        [Display(Name = "Last Name")]
        public string Lastname { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter your Username")]
        [Display(Name = "Username")]
        public string Username { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter your Password")]
        [StringLength(100, ErrorMessage = "The must be at least characters long.", MinimumLength = 8)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Required, EmailAddress]
        [Display(Name = "E-mail")]
        public string Email { get; set; }
    }
}
